name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_gcc:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: sudo apt-add-repository ppa:ubuntu-toolchain-r/test
    - run: sudo apt install g++-12
    - run: ./.travis-script.sh
      env:
        CC: gcc-12
        CXX: g++-12
        CXXFLAGS: -Wno-maybe-uninitialized -Wno-uninitialized

  build_clang_san:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: curl 'https://apt.llvm.org/llvm-snapshot.gpg.key' | sudo apt-key add -
    - run: sudo apt-add-repository ppa:ubuntu-toolchain-r/test
    - run: sudo apt-add-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main'
    - run: sudo apt install clang-16 g++-12
    - run: ./.travis-script.sh
      env:
        CC: clang-16
        CXX: clang++-16
        #CFLAGS: -fsanitize=undefined -fsanitize=address
        #CXXFLAGS: -fsanitize=undefined -fsanitize=address
        #LSAN_OPTIONS: detect_leaks=0
